services:
  - type: web
    name: magp-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python seed.py && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: ALLOWED_ORIGINS
        value: "*"
